### ISSUE TITLE
Projekt elkészült, v1.0 feltöltve

### ISSUE THREAD

**Issue by jostee** [Teaching-projects/SZE-Fordprog-2021-RS232#1]

**Comment by hegyhati** [comment]
Hat a nyelvtan resze eleg fapados,  emiatt igazabol 3-asra gondolnek, de feltetelezem a hardveres wrapper stb is tenyleg mukodik (kiprobalni ezt en most nem nagyon tudom) ZH-id rendeben voltak, szoval en erre igy egy joszivu 4-est tudok mondani.

**Comment by jostee** [comment]
Rendben, köszönöm.
Sajnos a nyelvtan részét nem tudtam tovább bontani, nem volt ennél komplexebb példám amivel bonyolultabbat össze tudtam volna állítani. Viszont a wrapper tényleg jól működik, így dll-ként befordítva lehet még implementálni is tudom majd napi használatba. :)

**Comment by hegyhati** [comment]
Akkor en ugy vettem, hogy a negyest elfogadtad, ezt be is irom. Minden jot a tovabbiakhoz!
